### ISSUE TITLE
Feature Request: d1-console login

### ISSUE THREAD

**Issue by jahands** [isaac-mcfadyen/d1-console#3]
Hi! First, love d1-console :) I could barely use D1 without it!

It'd be cool if there was a command to re-auth, like `d1-console login` - I accidently entered the wrong account ID and had to find where it was storing the creds to fix it (`$HOME/.d1`).

Along with this, `d1-console whoami` might be helpful, to see what I'm logged in as (I have multiple CF accounts.)

Thanks!

**Comment by rdvo** [comment]
same erorr here.. my creds dont work and dont know how to re-set

**Comment by isaac-mcfadyen** [comment]
Happy to say that I'll be working on this tomorrow as part of a rewrite 😄 

Until then, @ovived, you can remove the credentials by deleting the file at `~/.d1/credentials.json` on your computer and re-opening D1 Console.
