### ISSUE TITLE
Quiet Mode / Debug Info to Stderr

### ISSUE THREAD

**Issue by missinglink** [isaac-mcfadyen/d1-console#7]
Heya,

I would like to query D1 and get the json output in a shell stream.

For the following query I can't seem to get *only* the JSON data (without the `Welcome to D1 Console!`) and other info lines.

```bash
d1-console query -d example --execute 'SELECT * FROM sqlite_master;' --json
D1 Console v1.4.4
Welcome to D1 Console!
Enter a query followed by a semicolon to run it on the database. Multiple queries seperated by a semicolon will be run as a transaction (batch).
For more information, enter HELP;
Now querying database example (b0855cca-e921-4c9b-bff5-4f944581094d)
[
  {
    "type": "table",
    "name": "d1_kv",
    "tbl_name": "d1_kv",
    "rootpage": 2,
    "sql": "CREATE TABLE d1_kv (key TEXT PRIMARY KEY, value TEXT NOT NULL)"
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_d1_kv_1",
    "tbl_name": "d1_kv",
    "rootpage": 3,
    "sql": null
  }
]
```

I tried adding `2>/dev/null` to the command in order to send `stderr` to the bit bin, unfortunately that doesn't work 😢 

Some suggestions:
- add a `-silent` mode as per `spatialite`
- send informational messages to `stderr` instead of `stdout`

```bash
spatialite --help |& grep silent
   -silent              suppress the welcome message
```

**Comment by isaac-mcfadyen** [comment]
Hey @missinglink!

Just pushed a PR to add the silent flag - sorry it took me so long.
