### ISSUE TITLE
Cloudflare token permissions

### ISSUE THREAD

**Issue by deepdatalive** [isaac-mcfadyen/d1-console#8]
Hi can you please help me understand what all permissions are needed while creating the API key for d1-console?

**Comment by isaac-mcfadyen** [comment]
You'll need to provide D1 Edit permissions to edit your databases, or just Read permissions if you only want to read data with D1 Console.
<img width="882" alt="Screenshot 2023-06-05 at 08 20 32" src="https://github.com/isaac-mcfadyen/d1-console/assets/6243993/f45903ed-e192-44b7-a610-c7e972695828">

You can optionally scope the token to a specific account - for example, if you have multiple accounts all subscribed to D1, you can choose which one(s) this token is valid for.
<img width="570" alt="Screenshot 2023-06-05 at 08 21 25" src="https://github.com/isaac-mcfadyen/d1-console/assets/6243993/fd30bf01-7900-4ca4-ae05-6345ed3d3b87">

And finally, you can add a specific IP address to only allow that IP to use the token. Note that if you are on a residential internet connection your IP address may be shared or may change without warning so if things stop working keep that in mind.

**Comment by isaac-mcfadyen** [comment]
Closing this issue - feel free to ask for clarification if needed.

**Comment by deepdatalive** [comment]
Hi thanks really appreciate the information!
